from pydantic import  Field
from langgraph.graph import MessagesState

class ResearchAgentInputState(MessagesState):
    user_input: str = Field(..., description="The input query from the user.")

class ResearchAgentOutputState(MessagesState):
    research_summary: str = Field(
        ..., description="The summarized research findings generated by the agent."
    )
    research_documents: str = Field(
        ..., description="List of document URLs or references used in the research."
    )

class ResearchAgentState(ResearchAgentInputState, ResearchAgentOutputState):
    pass